# Generated by Django 4.1.7 on 2023-04-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('serviceid', models.IntegerField(primary_key=True, serialize=False)),
                ('servicenam', models.CharField(max_length=100)),
                ('servicedes', models.CharField(max_length=100)),
                ('serviceav', models.CharField(max_length=20)),
                ('servicepr', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
    ]
