# Generated by Django 4.1.7 on 2023-03-17 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proworkerApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proworkers',
            name='UrbanCity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proworkerApp.urbancity'),
        ),
    ]
