# Generated by Django 4.1.7 on 2023-03-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proworkerApp', '0002_alter_proworkers_urbancity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proworkers',
            name='UrbanCity',
            field=models.CharField(max_length=100),
        ),
    ]
