# Generated by Django 4.1.7 on 2023-04-23 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proworkerApp', '0003_alter_proworkers_urbancity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UrbanCity',
        ),
    ]
